print("welcome to python scripting")
print("we are working with some special charecterss")
print("welcome to python scripting. we are working with special charecters")
print("welcome to python scripting.\n we are working with special charecters")
print("welcome to python scripting.\b we are working with special charecters")
print("welcome to python scripting.\b\b we are working with special charecters")
print("welcome\tto python scripting\twe are working with\tspecial charecters")
